language: python

services:
  - docker

before_install:
  - "LABBASE_CHANGED=$(git diff --exit-code --name-only | grep labbase)"
  - "
    if [ $LABBASE_CHANGED = 'Dockerfile.jupyterlabbase' ]
    then
      BASE_IMAGE_VERSION=$(grep base_image_version Dockerfile.jupyterlabbase | awk -F '=' '{print $2}')
      docker build -t quay.io/esdc/esdl_single_user_labbase:${BASE_IMAGE_VERSION} -f Dockerfile.jupyterlabbase .
    fi
    "
  - docker build -t quay.io/esdc/esdl_single_user_lab:$TRAVIS_BRANCH -f Dockerfile.jupyterlab .
  - docker run -d quay.io/esdc/esdl_single_user_lab:$TRAVIS_BRANCH 'jupyter lab'
  - docker ps -a

script:
  - ls

before_deploy:
  - LABBASE_CHANGED=$(git diff --exit-code --name-only | grep labbase)
deploy:
  - provider: script
    script: bash docker_push_jupyterlabbase.sh
    skip_cleanup: true
    on:
      branch:  dzelge_pythonuserbase
      condition: $LABBASE_CHANGED = "Dockerfile.jupyterlabbase"
  - provider: script
    script: bash docker_push_jupyterlab.sh
    skip_cleanup: true
    on:
      branch:  dzelge_pythonuserbase
