language: python

services:
  - docker

before_install:
  - docker build -t quay.io/esdc/esdl_single_user_lab:0.6.1 -f Dockerfile.jupyterlab .
#  - docker run -d quay.io/esdc/esdl_single_user_lab:0.6.1 'jupyter lab'
#  - docker ps -a

script:
  - ls

deploy:
  provider: script
  script: bash docker_push.sh
  on:
    branch: alicja-25-synchronizing-jupyterhub-versions