language: python

services:
  - docker

before_install:
  - docker build -t quay.io/esdc/esdl_single_user_lab:$TRAVIS_BRANCH -f Dockerfile.jupyterlab .
  - docker run -d quay.io/esdc/esdl_single_user_lab:$TRAVIS_BRANCH 'jupyter lab'
  - docker ps -a

script:
  - ls

deploy:
  provider: script
  script: bash docker-push_jupyterlab.sh
  skip_cleanup: true
  on:
    branch:  dzelge_pythonuserbase
