language: python

services:
  - docker

before_install:
  - travis_wait 30 docker build -t quay.io/esdc/esdl_single_user_lab:$TRAVIS_BRANCH -f Dockerfile.jupyterlabbase .
  - travis_wait 30 docker build --build-arg var_name=${TRAVIS_BRANCH} -t quay.io/esdc/esdl_single_user_lab:$TRAVIS_BRANCH -f Dockerfile.jupyterlab .

script:
  - docker run -d quay.io/esdc/esdl_single_user_lab:$TRAVIS_BRANCH 'jupyter lab'
  - docker ps -a

deploy:
  skip_cleanup: true
  provider: script
  script: bash docker_push.sh
  on:
    all_branches: true