language: python

services:
  - docker

before_install:
  - docker build -t quay.io/esdc/esdl_single_user_lab:$TRAVIS_BRANCH -f Dockerfile.jupyterlab .
  - docker run -d quay.io/esdc/esdl_single_user_lab:$TRAVIS_BRANCH 'jupyter lab'
  - docker ps -a

script:
  - ls

deploy:
  skip_cleanup: true
  provider: script
  script: bash docker_push.sh
  on:
    all_branches: true